### ISSUE TITLE
NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger

### ISSUE THREAD

**Issue by efeint01** [SandroHc/reactive-jikan#11] opened 2022-02-21 18:03 UTC
`Jikan jikan = new Jikan()`

It throws an error on this line.

Full error:

java.lang.NoSuchMethodError: No static method getLogger(Ljava/lang/String;)Ljava/lang/System$Logger; in class Ljava/lang/System; or its super classes (declaration of 'java.lang.System' appears in /apex/com.android.art/javalib/core-oj.jar)

**Comment by SandroHc** [comment] 2022-02-21 18:32
Duplicate of #10. Will follow up on that issue.

**Closed as completed by SandroHc** 2022-02-21 18:32 UTC
